<?php

return [
	'marketplace_id' => 'ATVPDKIKX0DER',
    'seller_id' => 'A298JO187PGOK8',
    'access_key_id' => 'AKIAJ2XN5EGASDXJ3ZAQ',
    'secret_access_key' => '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',
    'MWSAuthToken' => 'amzn.mws.aab612e8-f157-c034-3f0c-4d6f1163f680',

    'carrierCodes' => [
    	'USPS',
		'UPS',
		'UPSMI',
		'FedEx',
		'DHL',
		'Fastway',
		'GLS',
		'GO!',
		'Hermes Logistik Gruppe',
		'Royal Mail',
		'Parcelforce',
		'City Link',
		'TNT',
		'Target',
		'SagawaExpress',
		'NipponExpress',
		'YamatoTransport',
		'DHL Global Mail',
		'UPS Mail Innovations',
		'FedEx SmartPost',
		'OSM',
		'OnTrac',
		'Streamlite',
		'Newgistics',
		'Canada Post',
		'Blue Package',
		'Chronopost',
		'Deutsche Post',
		'DPD',
		'La Poste',
		'Parcelnet',
		'Poste Italiane',
		'SDA',
		'Smartmail',
		'FEDEX_JP',
		'JP_EXPRESS',
		'NITTSU',
		'SAGAWA',
		'YAMATO',
		'BlueDart',
		'AFL/Fedex',
		'Aramex',
		'India Post',
		'Professional',
		'DTDC',
		'Overnite Express',
		'First Flight',
		'Delhivery',
		'Lasership',
		'Yodel',
		'Other',
		'Amazon Shipping',
		'Seur',
		'Correos',
		'MRW',
		'Endopack',
		'Chrono Express',
		'Nacex',
		'Otro',
		'Correios',
		'Toll Global Express',
		'China Post',
		'AUSSIE_POST',
		'EUB',
		'Australia Post',
		'Yun Express',
		'Fastway',
		'4PX',
		'YANWEN',
		'SF Express',
    ]
];