<?php

use Illuminate\Database\Seeder;
use TCG\Voyager\Models\DataType;

class DiscountsBreadRowAdded extends Seeder
{
    /**
     * Auto generated seed file
     *
     * @return void
     *
     * @throws Exception
     */
    public function run()
    {
        try {
            \DB::beginTransaction();

            $dataType = DataType::where('name', 'discounts')->first();

            \DB::table('data_rows')->insert(array (
                array (
                    'data_type_id' => $dataType->id,
                    'field' => 'id',
                    'type' => 'text',
                    'display_name' => 'Id',
                    'required' => 1,
                    'browse' => 0,
                    'read' => 0,
                    'edit' => 0,
                    'add' => 0,
                    'delete' => 0,
                    'details' => '{}',
                    'order' => 1,
                ),
                array (
                    'data_type_id' => $dataType->id,
                    'field' => 'created_at',
                    'type' => 'timestamp',
                    'display_name' => 'Created At',
                    'required' => 0,
                    'browse' => 0,
                    'read' => 0,
                    'edit' => 0,
                    'add' => 0,
                    'delete' => 0,
                    'details' => '{}',
                    'order' => 2,
                ),
                array (
                    'data_type_id' => $dataType->id,
                    'field' => 'updated_at',
                    'type' => 'timestamp',
                    'display_name' => 'Updated At',
                    'required' => 0,
                    'browse' => 0,
                    'read' => 0,
                    'edit' => 0,
                    'add' => 0,
                    'delete' => 0,
                    'details' => '{}',
                    'order' => 3,
                ),
                array (
                    'data_type_id' => $dataType->id,
                    'field' => 'name',
                    'type' => 'text',
                    'display_name' => 'Name',
                    'required' => 0,
                    'browse' => 1,
                    'read' => 1,
                    'edit' => 1,
                    'add' => 1,
                    'delete' => 1,
                    'details' => '{"display":{"width":"4"}}',
                    'order' => 4,
                ),
                array (
                    'data_type_id' => $dataType->id,
                    'field' => 'description',
                    'type' => 'text',
                    'display_name' => 'Description',
                    'required' => 0,
                    'browse' => 0,
                    'read' => 1,
                    'edit' => 1,
                    'add' => 1,
                    'delete' => 1,
                    'details' => '{}',
                    'order' => 5,
                ),
                array (
                    'data_type_id' => $dataType->id,
                    'field' => 'coupon_code',
                    'type' => 'text',
                    'display_name' => 'Coupon Code',
                    'required' => 1,
                    'browse' => 1,
                    'read' => 1,
                    'edit' => 1,
                    'add' => 1,
                    'delete' => 1,
                    'details' => '{}',
                    'order' => 6,
                ),
                array (
                    'data_type_id' => $dataType->id,
                    'field' => 'discount_type',
                    'type' => 'select_dropdown',
                    'display_name' => 'Field',
                    'required' => 1,
                    'browse' => 1,
                    'read' => 1,
                    'edit' => 1,
                    'add' => 1,
                    'delete' => 1,
                    'details' => '{"options":{"subtotal":"Subtotal","total":"Grand Total"},"display":{"width":"4"}}',
                    'order' => 7,
                ),
                array (
                    'data_type_id' => $dataType->id,
                    'field' => 'discount_method',
                    'type' => 'select_dropdown',
                    'display_name' => 'Method',
                    'required' => 1,
                    'browse' => 1,
                    'read' => 1,
                    'edit' => 1,
                    'add' => 1,
                    'delete' => 1,
                    'details' => '{"options":{"percentage":"Percentage off","dollars":"A Static price reduction"},"display":{"width":"4"}}',
                    'order' => 8,
                ),
                array (
                    'data_type_id' => $dataType->id,
                    'field' => 'discount_amount',
                    'type' => 'number',
                    'display_name' => 'Amount',
                    'required' => 1,
                    'browse' => 1,
                    'read' => 1,
                    'edit' => 1,
                    'add' => 1,
                    'delete' => 1,
                    'details' => '{"display":{"width":"4"}}',
                    'order' => 9,
                ),
                array (
                    'data_type_id' => $dataType->id,
                    'field' => 'activation_date',
                    'type' => 'date',
                    'display_name' => 'Activation Date',
                    'required' => 0,
                    'browse' => 0,
                    'read' => 0,
                    'edit' => 0,
                    'add' => 0,
                    'delete' => 0,
                    'details' => '{"display":{"width":"6"}}',
                    'order' => 10,
                ),
                array (
                    'data_type_id' => $dataType->id,
                    'field' => 'expiration_date',
                    'type' => 'date',
                    'display_name' => 'Expiration Date',
                    'required' => 0,
                    'browse' => 0,
                    'read' => 0,
                    'edit' => 0,
                    'add' => 0,
                    'delete' => 0,
                    'details' => '{"display":{"width":"6"}}',
                    'order' => 11,
                ),
                array (
                    'data_type_id' => $dataType->id,
                    'field' => 'is_triggerable',
                    'type' => 'checkbox',
                    'display_name' => 'Is Triggerable',
                    'required' => 0,
                    'browse' => 0,
                    'read' => 0,
                    'edit' => 0,
                    'add' => 0,
                    'delete' => 0,
                    'details' => '{"on":"Yes","off":"No"}',
                    'order' => 13,
                ),
                array (
                    'data_type_id' => $dataType->id,
                    'field' => 'trigger_amount',
                    'type' => 'text',
                    'display_name' => 'Trigger Amount',
                    'required' => 0,
                    'browse' => 0,
                    'read' => 0,
                    'edit' => 0,
                    'add' => 0,
                    'delete' => 0,
                    'details' => '{}',
                    'order' => 14,
                ),
                array (
                    'data_type_id' => $dataType->id,
                    'field' => 'collects_email',
                    'type' => 'checkbox',
                    'display_name' => 'Collects Email',
                    'required' => 0,
                    'browse' => 0,
                    'read' => 0,
                    'edit' => 0,
                    'add' => 0,
                    'delete' => 0,
                    'details' => '{"on":"Yes","off":"No"}',
                    'order' => 15,
                ),
                array (
                    'data_type_id' => $dataType->id,
                    'field' => 'discount_belongstomany_product_relationship',
                    'type' => 'relationship',
                    'display_name' => 'Products (leave empty for all)',
                    'required' => 0,
                    'browse' => 0,
                    'read' => 1,
                    'edit' => 1,
                    'add' => 1,
                    'delete' => 1,
                    'details' => '{"display":{"width":"6"},"model":"App\\\\Product","table":"products","type":"belongsToMany","column":"id","key":"id","label":"name","pivot_table":"discount_product","pivot":"1","taggable":"0"}',
                    'order' => 16,
                ),
                array (
                    'data_type_id' => $dataType->id,
                    'field' => 'is_active',
                    'type' => 'checkbox',
                    'display_name' => 'Enabled',
                    'required' => 1,
                    'browse' => 1,
                    'read' => 1,
                    'edit' => 1,
                    'add' => 1,
                    'delete' => 1,
                    'details' => '{"on":"Yes","off":"No"}',
                    'order' => 17,
                ),
                array (
                    'data_type_id' => $dataType->id,
                    'field' => 'shipping_id',
                    'type' => 'text',
                    'display_name' => 'Shipping Id',
                    'required' => 0,
                    'browse' => 0,
                    'read' => 0,
                    'edit' => 0,
                    'add' => 0,
                    'delete' => 0,
                    'details' => '{}',
                    'order' => 18,
                ),
                array (
                    'data_type_id' => $dataType->id,
                    'field' => 'deleted_at',
                    'type' => 'timestamp',
                    'display_name' => 'Deleted At',
                    'required' => 0,
                    'browse' => 0,
                    'read' => 0,
                    'edit' => 0,
                    'add' => 0,
                    'delete' => 0,
                    'details' => '{}',
                    'order' => 19,
                ),
            ));
        } catch(Exception $e) {
            throw new Exception('exception occur ' . $e);

            \DB::rollBack();
        }

        \DB::commit();
    }
}

