<?php

use Illuminate\Database\Seeder;
use TCG\Voyager\Models\DataType;

class OrdersBreadRowAdded extends Seeder
{
    /**
     * Auto generated seed file
     *
     * @return void
     *
     * @throws Exception
     */
    public function run()
    {
        try {
            \DB::beginTransaction();

            $dataType = DataType::where('name', 'orders')->first();

            \DB::table('data_rows')->insert(array (
                0 => 
                array (
                    'data_type_id' => $dataType->id,
                    'field' => 'id',
                    'type' => 'text',
                    'display_name' => 'Id',
                    'required' => 1,
                    'browse' => 0,
                    'read' => 0,
                    'edit' => 0,
                    'add' => 0,
                    'delete' => 0,
                    'details' => '{"display":{"width":3}}',
                    'order' => 1,
                ),
                1 => 
                array (
                    'data_type_id' => $dataType->id,
                    'field' => 'order_belongsto_order_status_relationship',
                    'type' => 'relationship',
                    'display_name' => 'order_status',
                    'required' => 0,
                    'browse' => 0,
                    'read' => 0,
                    'edit' => 1,
                    'add' => 1,
                    'delete' => 1,
                    'details' => '{"display":{"width":3},"model":"App\\\\OrderStatus","table":"order_statuses","type":"belongsTo","column":"order_status_id","key":"id","label":"name","pivot_table":"addresses","pivot":"0","taggable":"0"}',
                    'order' => 2,
                ),
                2 => 
                array (
                    'data_type_id' => $dataType->id,
                    'field' => 'order_belongsto_customer_relationship',
                    'type' => 'relationship',
                'display_name' => 'customer (if any)',
                    'required' => 0,
                    'browse' => 1,
                    'read' => 1,
                    'edit' => 0,
                    'add' => 0,
                    'delete' => 0,
                    'details' => '{"model":"App\\\\Customer","table":"customers","type":"belongsTo","column":"customer_id","key":"id","label":"name","pivot_table":"addresses","pivot":"0","taggable":"0"}',
                    'order' => 3,
                ),
                3 => 
                array (
                    'data_type_id' => $dataType->id,
                    'field' => 'order_belongstomany_product_relationship',
                    'type' => 'relationship',
                    'display_name' => 'products',
                    'required' => 0,
                    'browse' => 1,
                    'read' => 1,
                    'edit' => 0,
                    'add' => 0,
                    'delete' => 0,
                    'details' => '{"model":"\\\\App\\\\Product","table":"products","type":"belongsToMany","column":"id","key":"id","label":"name","pivot_table":"order_product","pivot":"1","taggable":"0"}',
                    'order' => 4,
                ),
                4 => 
                array (
                    'data_type_id' => $dataType->id,
                    'field' => 'order_hasmany_address_relationship',
                    'type' => 'relationship',
                    'display_name' => 'addresses',
                    'required' => 0,
                    'browse' => 1,
                    'read' => 1,
                    'edit' => 1,
                    'add' => 1,
                    'delete' => 1,
                    'details' => '{"model":"App\\\\Address","table":"addresses","type":"hasMany","column":"order_id","key":"id","label":"address_1","pivot_table":"addresses","pivot":"0","taggable":"0"}',
                    'order' => 5,
                ),
                5 => 
                array (
                    'data_type_id' => $dataType->id,
                    'field' => 'order_belongsto_shipping_relationship',
                    'type' => 'relationship',
                    'display_name' => 'shipping Method',
                    'required' => 0,
                    'browse' => 1,
                    'read' => 1,
                    'edit' => 1,
                    'add' => 1,
                    'delete' => 1,
                    'details' => '{"display":{"width":4},"model":"App\\\\Shipping","table":"shippings","type":"belongsTo","column":"id","key":"id","label":"name","pivot_table":"addresses","pivot":"0","taggable":"0"}',
                    'order' => 6,
                ),
                6 => 
                array (
                    'data_type_id' => $dataType->id,
                    'field' => 'order_belongsto_discount_relationship',
                    'type' => 'relationship',
                'display_name' => 'discount (if any)',
                    'required' => 0,
                    'browse' => 1,
                    'read' => 1,
                    'edit' => 1,
                    'add' => 1,
                    'delete' => 1,
                    'details' => '{"display":{"width":4},"model":"App\\\\Discount","table":"discounts","type":"belongsTo","column":"discount_id","key":"id","label":"coupon_code","pivot_table":"addresses","pivot":"0","taggable":"0"}',
                    'order' => 7,
                ),
                7 => 
                array (
                    'data_type_id' => $dataType->id,
                    'field' => 'discount_id',
                    'type' => 'text',
                    'display_name' => 'Discount Id',
                    'required' => 0,
                    'browse' => 0,
                    'read' => 0,
                    'edit' => 0,
                    'add' => 0,
                    'delete' => 0,
                    'details' => '{}',
                    'order' => 8,
                ),
                8 => 
                array (
                    'data_type_id' => $dataType->id,
                    'field' => 'name',
                    'type' => 'text',
                    'display_name' => 'Name',
                    'required' => 0,
                    'browse' => 1,
                    'read' => 1,
                    'edit' => 1,
                    'add' => 1,
                    'delete' => 1,
                    'details' => '{}',
                    'order' => 9,
                ),
                9 => 
                array (
                    'data_type_id' => $dataType->id,
                    'field' => 'email',
                    'type' => 'text',
                    'display_name' => 'Email',
                    'required' => 0,
                    'browse' => 1,
                    'read' => 1,
                    'edit' => 1,
                    'add' => 1,
                    'delete' => 1,
                    'details' => '{}',
                    'order' => 10,
                ),
                10 => 
                array (
                    'data_type_id' => $dataType->id,
                    'field' => 'phone',
                    'type' => 'text',
                    'display_name' => 'Phone',
                    'required' => 0,
                    'browse' => 1,
                    'read' => 1,
                    'edit' => 1,
                    'add' => 1,
                    'delete' => 1,
                    'details' => '{}',
                    'order' => 11,
                ),
                11 => 
                array (
                    'data_type_id' => $dataType->id,
                    'field' => 'payment_method',
                    'type' => 'text',
                    'display_name' => 'Payment Method',
                    'required' => 0,
                    'browse' => 1,
                    'read' => 1,
                    'edit' => 1,
                    'add' => 1,
                    'delete' => 1,
                    'details' => '{}',
                    'order' => 12,
                ),
                12 => 
                array (
                    'data_type_id' => $dataType->id,
                    'field' => 'transaction_id',
                    'type' => 'text',
                    'display_name' => 'Transaction Id',
                    'required' => 0,
                    'browse' => 0,
                    'read' => 0,
                    'edit' => 0,
                    'add' => 0,
                    'delete' => 0,
                    'details' => '{}',
                    'order' => 13,
                ),
                13 => 
                array (
                    'data_type_id' => $dataType->id,
                    'field' => 'cc_number',
                    'type' => 'text',
                    'display_name' => 'Cc Number',
                    'required' => 0,
                    'browse' => 0,
                    'read' => 1,
                    'edit' => 1,
                    'add' => 1,
                    'delete' => 1,
                    'details' => '{}',
                    'order' => 14,
                ),
                14 => 
                array (
                    'data_type_id' => $dataType->id,
                    'field' => 'cc_name',
                    'type' => 'text',
                    'display_name' => 'Cc Name',
                    'required' => 0,
                    'browse' => 0,
                    'read' => 1,
                    'edit' => 1,
                    'add' => 1,
                    'delete' => 1,
                    'details' => '{}',
                    'order' => 15,
                ),
                15 => 
                array (
                    'data_type_id' => $dataType->id,
                    'field' => 'cc_expiration',
                    'type' => 'text',
                    'display_name' => 'Cc Expiration',
                    'required' => 0,
                    'browse' => 0,
                    'read' => 1,
                    'edit' => 1,
                    'add' => 1,
                    'delete' => 1,
                    'details' => '{}',
                    'order' => 16,
                ),
                16 => 
                array (
                    'data_type_id' => $dataType->id,
                    'field' => 'cc_expiration_month',
                    'type' => 'text',
                    'display_name' => 'Cc Expiration Month',
                    'required' => 0,
                    'browse' => 0,
                    'read' => 1,
                    'edit' => 1,
                    'add' => 1,
                    'delete' => 1,
                    'details' => '{}',
                    'order' => 17,
                ),
                17 => 
                array (
                    'data_type_id' => $dataType->id,
                    'field' => 'cc_expiration_year',
                    'type' => 'text',
                    'display_name' => 'Cc Expiration Year',
                    'required' => 0,
                    'browse' => 0,
                    'read' => 1,
                    'edit' => 1,
                    'add' => 1,
                    'delete' => 1,
                    'details' => '{}',
                    'order' => 18,
                ),
                18 => 
                array (
                    'data_type_id' => $dataType->id,
                    'field' => 'cc_cvv',
                    'type' => 'text',
                    'display_name' => 'Cc Cvv',
                    'required' => 0,
                    'browse' => 0,
                    'read' => 1,
                    'edit' => 1,
                    'add' => 1,
                    'delete' => 1,
                    'details' => '{}',
                    'order' => 19,
                ),
                19 => 
                array (
                    'data_type_id' => $dataType->id,
                    'field' => 'card_type',
                    'type' => 'text',
                    'display_name' => 'Card Type',
                    'required' => 0,
                    'browse' => 0,
                    'read' => 1,
                    'edit' => 1,
                    'add' => 1,
                    'delete' => 1,
                    'details' => '{}',
                    'order' => 20,
                ),
                20 => 
                array (
                    'data_type_id' => $dataType->id,
                    'field' => 'discount_amount',
                    'type' => 'text',
                    'display_name' => 'Discount Amount',
                    'required' => 1,
                    'browse' => 1,
                    'read' => 1,
                    'edit' => 1,
                    'add' => 1,
                    'delete' => 1,
                    'details' => '{}',
                    'order' => 20,
                ),
                21 => 
                array (
                    'data_type_id' => $dataType->id,
                    'field' => 'gclid',
                    'type' => 'text',
                    'display_name' => 'Gclid',
                    'required' => 0,
                    'browse' => 0,
                    'read' => 1,
                    'edit' => 1,
                    'add' => 1,
                    'delete' => 1,
                    'details' => '{}',
                    'order' => 21,
                ),
                22 => 
                array (
                    'data_type_id' => $dataType->id,
                    'field' => 'tax_rate',
                    'type' => 'text',
                    'display_name' => 'Tax Rate',
                    'required' => 1,
                    'browse' => 0,
                    'read' => 1,
                    'edit' => 1,
                    'add' => 1,
                    'delete' => 1,
                    'details' => '{}',
                    'order' => 22,
                ),
                23 => 
                array (
                    'data_type_id' => $dataType->id,
                    'field' => 'tax',
                    'type' => 'text',
                    'display_name' => 'Tax',
                    'required' => 1,
                    'browse' => 0,
                    'read' => 1,
                    'edit' => 1,
                    'add' => 1,
                    'delete' => 1,
                    'details' => '{}',
                    'order' => 23,
                ),
                24 => 
                array (
                    'data_type_id' => $dataType->id,
                    'field' => 'shipping_cost',
                    'type' => 'text',
                    'display_name' => 'Shipping Cost',
                    'required' => 1,
                    'browse' => 0,
                    'read' => 1,
                    'edit' => 1,
                    'add' => 1,
                    'delete' => 1,
                    'details' => '{}',
                    'order' => 24,
                ),
                25 => 
                array (
                    'data_type_id' => $dataType->id,
                    'field' => 'subtotal',
                    'type' => 'text',
                    'display_name' => 'Subtotal',
                    'required' => 1,
                    'browse' => 1,
                    'read' => 1,
                    'edit' => 1,
                    'add' => 1,
                    'delete' => 1,
                    'details' => '{}',
                    'order' => 25,
                ),
                26 => 
                array (
                    'data_type_id' => $dataType->id,
                    'field' => 'total',
                    'type' => 'text',
                    'display_name' => 'Total',
                    'required' => 1,
                    'browse' => 0,
                    'read' => 1,
                    'edit' => 1,
                    'add' => 1,
                    'delete' => 1,
                    'details' => '{}',
                    'order' => 26,
                ),
                27 => 
                array (
                    'data_type_id' => $dataType->id,
                    'field' => 'confirmed',
                    'type' => 'text',
                    'display_name' => 'Confirmed',
                    'required' => 1,
                    'browse' => 1,
                    'read' => 1,
                    'edit' => 1,
                    'add' => 1,
                    'delete' => 1,
                    'details' => '{}',
                    'order' => 27,
                ),
                28 => 
                array (
                    'data_type_id' => $dataType->id,
                    'field' => 'confirmed_at',
                    'type' => 'timestamp',
                    'display_name' => 'Confirmed At',
                    'required' => 0,
                    'browse' => 0,
                    'read' => 1,
                    'edit' => 1,
                    'add' => 1,
                    'delete' => 1,
                    'details' => '{}',
                    'order' => 28,
                ),
                29 => 
                array (
                    'data_type_id' => $dataType->id,
                    'field' => 'api_sales_order_id',
                    'type' => 'text',
                    'display_name' => 'Api Sales Order Id',
                    'required' => 0,
                    'browse' => 1,
                    'read' => 1,
                    'edit' => 1,
                    'add' => 1,
                    'delete' => 1,
                    'details' => '{}',
                    'order' => 28,
                ),
                30 => 
                array (
                    'data_type_id' => $dataType->id,
                    'field' => 'mailed',
                    'type' => 'text',
                    'display_name' => 'Mailed',
                    'required' => 0,
                    'browse' => 0,
                    'read' => 1,
                    'edit' => 1,
                    'add' => 1,
                    'delete' => 1,
                    'details' => '{}',
                    'order' => 29,
                ),
                31 => 
                array (
                    'data_type_id' => $dataType->id,
                    'field' => 'api_purchase_order_id',
                    'type' => 'text',
                    'display_name' => 'Api Purchase Order Id',
                    'required' => 0,
                    'browse' => 1,
                    'read' => 1,
                    'edit' => 1,
                    'add' => 1,
                    'delete' => 1,
                    'details' => '{}',
                    'order' => 29,
                ),
                32 => 
                array (
                    'data_type_id' => $dataType->id,
                    'field' => 'mailed_at',
                    'type' => 'timestamp',
                    'display_name' => 'Mailed At',
                    'required' => 0,
                    'browse' => 0,
                    'read' => 1,
                    'edit' => 1,
                    'add' => 1,
                    'delete' => 1,
                    'details' => '{}',
                    'order' => 30,
                ),
                33 => 
                array (
                    'data_type_id' => $dataType->id,
                    'field' => 'api_customer_id',
                    'type' => 'text',
                    'display_name' => 'Api Customer Id',
                    'required' => 0,
                    'browse' => 1,
                    'read' => 1,
                    'edit' => 1,
                    'add' => 1,
                    'delete' => 1,
                    'details' => '{}',
                    'order' => 30,
                ),
                34 => 
                array (
                    'data_type_id' => $dataType->id,
                    'field' => 'deleted_at',
                    'type' => 'timestamp',
                    'display_name' => 'Deleted At',
                    'required' => 0,
                    'browse' => 0,
                    'read' => 1,
                    'edit' => 1,
                    'add' => 1,
                    'delete' => 1,
                    'details' => '{}',
                    'order' => 31,
                ),
                35 => 
                array (
                    'data_type_id' => $dataType->id,
                    'field' => 'api_requested_at',
                    'type' => 'timestamp',
                    'display_name' => 'Api Requested At',
                    'required' => 0,
                    'browse' => 1,
                    'read' => 1,
                    'edit' => 1,
                    'add' => 1,
                    'delete' => 1,
                    'details' => '{}',
                    'order' => 31,
                ),
                36 => 
                array (
                    'data_type_id' => $dataType->id,
                    'field' => 'created_at',
                    'type' => 'timestamp',
                    'display_name' => 'Created At',
                    'required' => 0,
                    'browse' => 1,
                    'read' => 1,
                    'edit' => 1,
                    'add' => 0,
                    'delete' => 1,
                    'details' => '{}',
                    'order' => 32,
                ),
                37 => 
                array (
                    'data_type_id' => $dataType->id,
                    'field' => 'is_reported',
                    'type' => 'text',
                    'display_name' => 'Is Reported',
                    'required' => 1,
                    'browse' => 1,
                    'read' => 1,
                    'edit' => 1,
                    'add' => 1,
                    'delete' => 1,
                    'details' => '{}',
                    'order' => 32,
                ),
                38 => 
                array (
                    'data_type_id' => $dataType->id,
                    'field' => 'updated_at',
                    'type' => 'timestamp',
                    'display_name' => 'Updated At',
                    'required' => 0,
                    'browse' => 0,
                    'read' => 0,
                    'edit' => 0,
                    'add' => 0,
                    'delete' => 0,
                    'details' => '{}',
                    'order' => 33,
                ),
                39 => 
                array (
                    'data_type_id' => $dataType->id,
                    'field' => 'reported_at',
                    'type' => 'timestamp',
                    'display_name' => 'Reported At',
                    'required' => 0,
                    'browse' => 1,
                    'read' => 1,
                    'edit' => 1,
                    'add' => 1,
                    'delete' => 1,
                    'details' => '{}',
                    'order' => 33,
                ),
                40 => 
                array (
                    'data_type_id' => $dataType->id,
                    'field' => 'order_status_id',
                    'type' => 'text',
                    'display_name' => 'Order Status Id',
                    'required' => 0,
                    'browse' => 0,
                    'read' => 0,
                    'edit' => 0,
                    'add' => 0,
                    'delete' => 0,
                    'details' => '{}',
                    'order' => 34,
                ),
                41 => 
                array (
                    'data_type_id' => $dataType->id,
                    'field' => 'customer_id',
                    'type' => 'text',
                    'display_name' => 'Customer Id',
                    'required' => 0,
                    'browse' => 0,
                    'read' => 0,
                    'edit' => 0,
                    'add' => 0,
                    'delete' => 0,
                    'details' => '{}',
                    'order' => 36,
                ),
            ));
        } catch(Exception $e) {
            throw new Exception('exception occur ' . $e);

            \DB::rollBack();
        }

        \DB::commit();
    }
}

