<?php

use Illuminate\Database\Seeder;
use TCG\Voyager\Models\DataType;

class ProductsBreadRowAdded extends Seeder
{
    /**
     * Auto generated seed file
     *
     * @return void
     *
     * @throws Exception
     */
    public function run()
    {
        try {
            \DB::beginTransaction();

            $dataType = DataType::where('name', 'products')->first();

            \DB::table('data_rows')->insert(array (
                0 => 
                array (
                    'data_type_id' => $dataType->id,
                    'field' => 'id',
                    'type' => 'text',
                    'display_name' => 'Id',
                    'required' => 1,
                    'browse' => 0,
                    'read' => 0,
                    'edit' => 0,
                    'add' => 0,
                    'delete' => 0,
                    'details' => '{}',
                    'order' => 1,
                ),
                1 => 
                array (
                    'data_type_id' => $dataType->id,
                    'field' => 'parent_id',
                    'type' => 'text',
                    'display_name' => 'Parent Id',
                    'required' => 0,
                    'browse' => 1,
                    'read' => 1,
                    'edit' => 1,
                    'add' => 1,
                    'delete' => 1,
                    'details' => '{}',
                    'order' => 2,
                ),
                2 => 
                array (
                    'data_type_id' => $dataType->id,
                    'field' => 'brand_id',
                    'type' => 'text',
                    'display_name' => 'Brand Id',
                    'required' => 0,
                    'browse' => 1,
                    'read' => 1,
                    'edit' => 1,
                    'add' => 1,
                    'delete' => 1,
                    'details' => '{}',
                    'order' => 3,
                ),
                3 => 
                array (
                    'data_type_id' => $dataType->id,
                    'field' => 'manufacture_id',
                    'type' => 'text',
                    'display_name' => 'Manufacture Id',
                    'required' => 0,
                    'browse' => 1,
                    'read' => 1,
                    'edit' => 1,
                    'add' => 1,
                    'delete' => 1,
                    'details' => '{}',
                    'order' => 4,
                ),
                4 => 
                array (
                    'data_type_id' => $dataType->id,
                    'field' => 'availability_id',
                    'type' => 'text',
                    'display_name' => 'Availability Id',
                    'required' => 0,
                    'browse' => 1,
                    'read' => 1,
                    'edit' => 1,
                    'add' => 1,
                    'delete' => 1,
                    'details' => '{}',
                    'order' => 5,
                ),
                5 => 
                array (
                    'data_type_id' => $dataType->id,
                    'field' => 'name',
                    'type' => 'text',
                    'display_name' => 'Name',
                    'required' => 0,
                    'browse' => 1,
                    'read' => 1,
                    'edit' => 1,
                    'add' => 1,
                    'delete' => 1,
                    'details' => '{}',
                    'order' => 6,
                ),
                6 => 
                array (
                    'data_type_id' => $dataType->id,
                    'field' => 'slug',
                    'type' => 'text',
                    'display_name' => 'Slug',
                    'required' => 1,
                    'browse' => 1,
                    'read' => 1,
                    'edit' => 1,
                    'add' => 1,
                    'delete' => 1,
                    'details' => '{}',
                    'order' => 7,
                ),
                8 => 
                array (
                    'data_type_id' => $dataType->id,
                    'field' => 'sku',
                    'type' => 'text',
                    'display_name' => 'Sku',
                    'required' => 0,
                    'browse' => 1,
                    'read' => 1,
                    'edit' => 1,
                    'add' => 1,
                    'delete' => 1,
                    'details' => '{}',
                    'order' => 9,
                ),
                9 => 
                array (
                    'data_type_id' => $dataType->id,
                    'field' => 'upc',
                    'type' => 'text',
                    'display_name' => 'Upc',
                    'required' => 0,
                    'browse' => 1,
                    'read' => 1,
                    'edit' => 1,
                    'add' => 1,
                    'delete' => 1,
                    'details' => '{}',
                    'order' => 10,
                ),
                10 => 
                array (
                    'data_type_id' => $dataType->id,
                    'field' => 'cost',
                    'type' => 'text',
                    'display_name' => 'Cost',
                    'required' => 1,
                    'browse' => 1,
                    'read' => 1,
                    'edit' => 1,
                    'add' => 1,
                    'delete' => 1,
                    'details' => '{}',
                    'order' => 11,
                ),
                11 => 
                array (
                    'data_type_id' => $dataType->id,
                    'field' => 'price',
                    'type' => 'text',
                    'display_name' => 'Price',
                    'required' => 1,
                    'browse' => 1,
                    'read' => 1,
                    'edit' => 1,
                    'add' => 1,
                    'delete' => 1,
                    'details' => '{}',
                    'order' => 12,
                ),
                12 => 
                array (
                    'data_type_id' => $dataType->id,
                    'field' => 'status',
                    'type' => 'checkbox',
                    'display_name' => 'Status',
                    'required' => 1,
                    'browse' => 1,
                    'read' => 1,
                    'edit' => 1,
                    'add' => 1,
                    'delete' => 1,
                    'details' => '{"on":"Enabled","off":"Disabled"}',
                    'order' => 13,
                ),
                13 => 
                array (
                    'data_type_id' => $dataType->id,
                    'field' => 'quantity',
                    'type' => 'number',
                    'display_name' => 'Quantity',
                    'required' => 1,
                    'browse' => 1,
                    'read' => 1,
                    'edit' => 1,
                    'add' => 1,
                    'delete' => 1,
                    'details' => '{}',
                    'order' => 14,
                ),
                14 => 
                array (
                    'data_type_id' => $dataType->id,
                    'field' => 'quantity_per_case',
                    'type' => 'text',
                    'display_name' => 'Quantity Per Case',
                    'required' => 0,
                    'browse' => 1,
                    'read' => 1,
                    'edit' => 1,
                    'add' => 1,
                    'delete' => 1,
                    'details' => '{}',
                    'order' => 15,
                ),
                15 => 
                array (
                    'data_type_id' => $dataType->id,
                    'field' => 'short_description',
                    'type' => 'text',
                    'display_name' => 'Short Description',
                    'required' => 0,
                    'browse' => 1,
                    'read' => 1,
                    'edit' => 1,
                    'add' => 1,
                    'delete' => 1,
                    'details' => '{}',
                    'order' => 16,
                ),
                16 => 
                array (
                    'data_type_id' => $dataType->id,
                    'field' => 'description',
                    'type' => 'rich_text_box',
                    'display_name' => 'Description',
                    'required' => 0,
                    'browse' => 1,
                    'read' => 1,
                    'edit' => 1,
                    'add' => 1,
                    'delete' => 1,
                    'details' => '{}',
                    'order' => 17,
                ),
                17 => 
                array (
                    'data_type_id' => $dataType->id,
                    'field' => 'item_features',
                    'type' => 'text',
                    'display_name' => 'Item Features',
                    'required' => 0,
                    'browse' => 1,
                    'read' => 1,
                    'edit' => 1,
                    'add' => 1,
                    'delete' => 1,
                    'details' => '{}',
                    'order' => 18,
                ),
                18 => 
                array (
                    'data_type_id' => $dataType->id,
                    'field' => 'weight_uom',
                    'type' => 'text',
                    'display_name' => 'Weight Uom',
                    'required' => 0,
                    'browse' => 0,
                    'read' => 1,
                    'edit' => 1,
                    'add' => 1,
                    'delete' => 1,
                    'details' => '{}',
                    'order' => 19,
                ),
                19 => 
                array (
                    'data_type_id' => $dataType->id,
                    'field' => 'length_uom',
                    'type' => 'text',
                    'display_name' => 'Length Uom',
                    'required' => 0,
                    'browse' => 0,
                    'read' => 1,
                    'edit' => 1,
                    'add' => 1,
                    'delete' => 1,
                    'details' => '{}',
                    'order' => 20,
                ),
                20 => 
                array (
                    'data_type_id' => $dataType->id,
                    'field' => 'height_uom',
                    'type' => 'text',
                    'display_name' => 'Height Uom',
                    'required' => 0,
                    'browse' => 0,
                    'read' => 1,
                    'edit' => 1,
                    'add' => 1,
                    'delete' => 1,
                    'details' => '{}',
                    'order' => 21,
                ),
                21 => 
                array (
                    'data_type_id' => $dataType->id,
                    'field' => 'width_uom',
                    'type' => 'text',
                    'display_name' => 'Width Uom',
                    'required' => 0,
                    'browse' => 0,
                    'read' => 1,
                    'edit' => 1,
                    'add' => 1,
                    'delete' => 1,
                    'details' => '{}',
                    'order' => 22,
                ),
                22 => 
                array (
                    'data_type_id' => $dataType->id,
                    'field' => 'weight',
                    'type' => 'text',
                    'display_name' => 'Weight',
                    'required' => 0,
                    'browse' => 0,
                    'read' => 1,
                    'edit' => 1,
                    'add' => 1,
                    'delete' => 1,
                    'details' => '{}',
                    'order' => 23,
                ),
                23 => 
                array (
                    'data_type_id' => $dataType->id,
                    'field' => 'width',
                    'type' => 'text',
                    'display_name' => 'Width',
                    'required' => 0,
                    'browse' => 0,
                    'read' => 1,
                    'edit' => 1,
                    'add' => 1,
                    'delete' => 1,
                    'details' => '{}',
                    'order' => 24,
                ),
                24 => 
                array (
                    'data_type_id' => $dataType->id,
                    'field' => 'height',
                    'type' => 'text',
                    'display_name' => 'Height',
                    'required' => 0,
                    'browse' => 0,
                    'read' => 1,
                    'edit' => 1,
                    'add' => 1,
                    'delete' => 1,
                    'details' => '{}',
                    'order' => 25,
                ),
                25 => 
                array (
                    'data_type_id' => $dataType->id,
                    'field' => 'length',
                    'type' => 'text',
                    'display_name' => 'Length',
                    'required' => 0,
                    'browse' => 0,
                    'read' => 1,
                    'edit' => 1,
                    'add' => 1,
                    'delete' => 1,
                    'details' => '{}',
                    'order' => 26,
                ),
                26 => 
                array (
                    'data_type_id' => $dataType->id,
                    'field' => 'clicks_counter',
                    'type' => 'text',
                    'display_name' => 'Clicks Counter',
                    'required' => 1,
                    'browse' => 1,
                    'read' => 1,
                    'edit' => 1,
                    'add' => 1,
                    'delete' => 1,
                    'details' => '{}',
                    'order' => 27,
                ),
                27 => 
                array (
                    'data_type_id' => $dataType->id,
                    'field' => 'pack',
                    'type' => 'text',
                    'display_name' => 'Pack',
                    'required' => 0,
                    'browse' => 1,
                    'read' => 1,
                    'edit' => 1,
                    'add' => 1,
                    'delete' => 1,
                    'details' => '{}',
                    'order' => 27,
                ),
                28 => 
                array (
                    'data_type_id' => $dataType->id,
                    'field' => 'sales_count',
                    'type' => 'text',
                    'display_name' => 'Sales Count',
                    'required' => 1,
                    'browse' => 1,
                    'read' => 1,
                    'edit' => 1,
                    'add' => 1,
                    'delete' => 1,
                    'details' => '{}',
                    'order' => 28,
                ),
                29 => 
                array (
                    'data_type_id' => $dataType->id,
                    'field' => 'size',
                    'type' => 'text',
                    'display_name' => 'Size',
                    'required' => 0,
                    'browse' => 1,
                    'read' => 1,
                    'edit' => 1,
                    'add' => 1,
                    'delete' => 1,
                    'details' => '{}',
                    'order' => 28,
                ),
                30 => 
                array (
                    'data_type_id' => $dataType->id,
                    'field' => 'created_at',
                    'type' => 'timestamp',
                    'display_name' => 'Created At',
                    'required' => 0,
                    'browse' => 1,
                    'read' => 1,
                    'edit' => 1,
                    'add' => 0,
                    'delete' => 1,
                    'details' => '{}',
                    'order' => 29,
                ),
                31 => 
                array (
                    'data_type_id' => $dataType->id,
                    'field' => 'size_uom',
                    'type' => 'text',
                    'display_name' => 'Size Uom',
                    'required' => 0,
                    'browse' => 1,
                    'read' => 1,
                    'edit' => 1,
                    'add' => 1,
                    'delete' => 1,
                    'details' => '{}',
                    'order' => 29,
                ),
                32 => 
                array (
                    'data_type_id' => $dataType->id,
                    'field' => 'updated_at',
                    'type' => 'timestamp',
                    'display_name' => 'Updated At',
                    'required' => 0,
                    'browse' => 0,
                    'read' => 0,
                    'edit' => 0,
                    'add' => 0,
                    'delete' => 0,
                    'details' => '{}',
                    'order' => 30,
                ),
                33 => 
                array (
                    'data_type_id' => $dataType->id,
                    'field' => 'homepage_order',
                    'type' => 'text',
                    'display_name' => 'Homepage Order',
                    'required' => 0,
                    'browse' => 1,
                    'read' => 1,
                    'edit' => 1,
                    'add' => 1,
                    'delete' => 1,
                    'details' => '{}',
                    'order' => 34,
                ),
                34 => 
                array (
                    'data_type_id' => $dataType->id,
                    'field' => 'frozen',
                    'type' => 'text',
                    'display_name' => 'Frozen',
                    'required' => 1,
                    'browse' => 1,
                    'read' => 1,
                    'edit' => 1,
                    'add' => 1,
                    'delete' => 1,
                    'details' => '{}',
                    'order' => 35,
                ),
                35 => 
                array (
                    'data_type_id' => $dataType->id,
                    'field' => 'mpn',
                    'type' => 'text',
                    'display_name' => 'Mpn',
                    'required' => 0,
                    'browse' => 1,
                    'read' => 1,
                    'edit' => 1,
                    'add' => 1,
                    'delete' => 1,
                    'details' => '{}',
                    'order' => 36,
                ),
                36 => 
                array (
                    'data_type_id' => $dataType->id,
                    'field' => 'vendor_code',
                    'type' => 'text',
                    'display_name' => 'Vendor Code',
                    'required' => 0,
                    'browse' => 1,
                    'read' => 1,
                    'edit' => 1,
                    'add' => 1,
                    'delete' => 1,
                    'details' => '{}',
                    'order' => 37,
                ),
                37 => 
                array (
                    'data_type_id' => $dataType->id,
                    'field' => 'is_ignored',
                    'type' => 'text',
                    'display_name' => 'Is Ignored',
                    'required' => 1,
                    'browse' => 1,
                    'read' => 1,
                    'edit' => 1,
                    'add' => 1,
                    'delete' => 1,
                    'details' => '{}',
                    'order' => 38,
                ),
            ));
        } catch(Exception $e) {
            throw new Exception('exception occur ' . $e);

            \DB::rollBack();
        }

        \DB::commit();
    }
}

