<?php

use Illuminate\Database\Seeder;

class ProductsTableSeeder extends Seeder
{
    /**
     * Auto generated seed file
     *
     * @return void
     *
     * @throws Exception
     */
    public function run()
    {
     try {
        \DB::beginTransaction();

        \DB::table('products')->delete();

        $products = array (
                0 => 
                array (
                    'id' => 1,
                    'name' => 'Bamboo Vegetable Brush',
                    'slug' => 'bamboo-vegetable-brush',
                    'sku' => '281',
                    'upc' => '7-16554-00281-9',
                    'quantity_per_case' => '6',
                    'weight_uom' => 'lbs',
                    'length_uom' => 'in',
                    'height_uom' => 'in',
                    'width_uom' => 'in',
                    'weight' => '0.40',
                    'width' => '2.50',
                    'height' => '6.00',
                    'length' => '4.00',
                    'clicks_counter' => 0,
                    'sales_count' => 0,
                    'parent_id' => NULL,
                    'homepage_order' => NULL,
                ),
                1 => 
                array (
                    'id' => 2,
                    'name' => 'Bamboo Dish Brush',
                    'slug' => 'bamboo-dish-brush',
                    'sku' => '280',
                    'upc' => '7-16554-00280-2',
                    'quantity_per_case' => '6',
                    'weight_uom' => 'lbs',
                    'length_uom' => 'in',
                    'height_uom' => 'in',
                    'width_uom' => 'in',
                    'weight' => '0.45',
                    'width' => '2.25',
                    'height' => '11.25',
                    'length' => '4.00',
                    'clicks_counter' => 0,
                    'sales_count' => 0,
                    'parent_id' => NULL,
                    'homepage_order' => NULL,
                ),
                2 => 
                array (
                    'id' => 3,
                    'name' => 'Bamboo Bottle Brush',
                    'slug' => 'bamboo-bottle-brush',
                    'sku' => '279',
                    'upc' => '7-16554-00279-6',
                    'quantity_per_case' => '6',
                    'weight_uom' => 'lbs',
                    'length_uom' => 'in',
                    'height_uom' => 'in',
                    'width_uom' => 'in',
                    'weight' => '0.55',
                    'width' => '2.50',
                    'height' => '13.00',
                    'length' => '4.00',
                    'clicks_counter' => 0,
                    'sales_count' => 0,
                    'parent_id' => NULL,
                    'homepage_order' => NULL,
                ),
                3 => 
                array (
                    'id' => 4,
                    'name' => 'Bamboo Drying Cloth - 2 Pack',
                    'slug' => 'bamboo-drying-cloth-2-pack',
                    'sku' => '293',
                    'upc' => '7-16554-00293-2',
                    'quantity_per_case' => '12 / 24',
                    'weight_uom' => 'lbs',
                    'length_uom' => 'in',
                    'height_uom' => 'in',
                    'width_uom' => 'in',
                    'weight' => '0.20',
                    'width' => '0.50',
                    'height' => '8.00',
                    'length' => '6.00',
                    'clicks_counter' => 0,
                    'sales_count' => 0,
                    'parent_id' => NULL,
                    'homepage_order' => NULL,
                ),
                4 => 
                array (
                    'id' => 5,
                'name' => 'Compostable Food Handling Glove - 200 Pairs of Gloves (one size fits all)',
                    'slug' => 'compostable-food-handling-glove-200-pairs-of-gloves-one-size-fits-all',
                    'sku' => '651',
                    'upc' => NULL,
                    'quantity_per_case' => '24',
                    'weight_uom' => 'lbs',
                    'length_uom' => 'in',
                    'height_uom' => 'in',
                    'width_uom' => 'in',
                    'weight' => '0.00',
                    'width' => '0.00',
                    'height' => '0.00',
                    'length' => '0.00',
                    'clicks_counter' => 0,
                    'sales_count' => 0,
                    'parent_id' => NULL,
                    'homepage_order' => NULL,
                ),
                5 => 
                array (
                    'id' => 6,
                'name' => 'Compostable Food Handling Glove - 500 Pairs of Gloves (one size fits all)',
                    'slug' => 'compostable-food-handling-glove-500-pairs-of-gloves-one-size-fits-all',
                    'sku' => NULL,
                    'upc' => NULL,
                    'quantity_per_case' => '24',
                    'weight_uom' => 'lbs',
                    'length_uom' => 'in',
                    'height_uom' => 'in',
                    'width_uom' => 'in',
                    'weight' => '0.00',
                    'width' => '0.00',
                    'height' => '0.00',
                    'length' => '0.00',
                    'clicks_counter' => 0,
                    'sales_count' => 0,
                    'parent_id' => '651',
                    'homepage_order' => NULL,
                ),
                6 => 
                array (
                    'id' => 7,
                    'name' => 'Bamboo Sponge - 2 Pack',
                    'slug' => 'bamboo-sponge-2-pack',
                    'sku' => '292',
                    'upc' => '7-16554-00292-5',
                    'cost' => '0.000000',
                    'price' => '6.990000',
                    'quantity_per_case' => '12 / 24',
                    'weight_uom' => 'lbs',
                    'length_uom' => 'in',
                    'height_uom' => 'in',
                    'width_uom' => 'in',
                    'weight' => '0.14',
                    'width' => '3.15',
                    'height' => '1.97',
                    'length' => '5.12',
                    'clicks_counter' => 0,
                    'sales_count' => 0,
                    'parent_id' => NULL,
                    'homepage_order' => NULL,
                ),
                7 => 
                array (
                    'id' => 8,
                    'name' => 'Bamboo Sponge - 24 Pack',
                    'slug' => 'bamboo-sponge-24-pack',
                    'item_id' => '282',
                    'sku' => '282',
                    'upc' => '7-16554-00282-6',
                    'quantity_per_case' => NULL,
                    'weight_uom' => 'lbs',
                    'length_uom' => 'in',
                    'height_uom' => 'in',
                    'width_uom' => 'in',
                    'weight' => '0.00',
                    'width' => '0.00',
                    'height' => '0.00',
                    'length' => '0.00',
                    'clicks_counter' => 0,
                    'sales_count' => 0,
                    'parent_id' => '292',
                    'homepage_order' => NULL,
                ),
                8 => 
                array (
                    'id' => 9,
                    'name' => 'Bamboo Pet Sponge - 2 Packs',
                    'slug' => 'bamboo-pet-sponge-2-packs',
                    'item_id' => '610',
                    'sku' => '610',
                    'upc' => '7-16554-00610-7',
                    'quantity_per_case' => '12',
                    'weight_uom' => 'lbs',
                    'length_uom' => 'in',
                    'height_uom' => 'in',
                    'width_uom' => 'in',
                    'weight' => '0.00',
                    'width' => '0.00',
                    'height' => '0.00',
                    'length' => '0.00',
                    'clicks_counter' => 0,
                    'sales_count' => 0,
                    'parent_id' => NULL,
                    'homepage_order' => NULL,
                ),
                9 => 
                array (
                    'id' => 10,
                    'name' => 'Bamboo Toilet Paper - 6 Rolls - 400 Sheets / Roll',
                    'slug' => 'bamboo-toilet-paper-6-rolls-400-sheets-roll',
                    'item_id' => '299',
                    'sku' => '299',
                    'upc' => '7-16554-00299-4',
                    'cost' => '0.000000',
                    'price' => '10.990000',
                    'quantity_per_case' => '8',
                    'weight_uom' => 'lbs',
                    'length_uom' => 'in',
                    'height_uom' => 'in',
                    'width_uom' => 'in',
                    'weight' => '1.64',
                    'width' => '4.45',
                    'height' => '7.87',
                    'length' => '13.00',
                    'clicks_counter' => 0,
                    'sales_count' => 0,
                    'parent_id' => NULL,
                    'homepage_order' => NULL,
                ),
                10 => 
                array (
                    'id' => 11,
                    'name' => 'Bamboo Toilet Paper - 4 Rolls - 320 Sheets / Roll',
                    'slug' => 'bamboo-toilet-paper-4-rolls-320-sheets-roll',
                    'item_id' => '612',
                    'sku' => '612',
                    'upc' => '7-16554-00612-1',
                    'quantity_per_case' => '12',
                    'weight_uom' => 'lbs',
                    'length_uom' => 'in',
                    'height_uom' => 'in',
                    'width_uom' => 'in',
                    'weight' => '0.00',
                    'width' => '4.00',
                    'height' => '8.50',
                    'length' => '8.50',
                    'clicks_counter' => 0,
                    'sales_count' => 0,
                    'parent_id' => NULL,
                    'homepage_order' => NULL,
                ),
                11 => 
                array (
                    'id' => 12,
                    'name' => 'Perforated Towels - 25 Sheets',
                    'slug' => 'perforated-towels-25-sheets',
                    'item_id' => '295',
                    'sku' => '295',
                    'upc' => '7-16554-00295-6',
                    'cost' => '0.000000',
                    'price' => '7.990000',
                    'quantity_per_case' => '12',
                    'weight_uom' => 'lbs',
                    'length_uom' => 'in',
                    'height_uom' => 'in',
                    'width_uom' => 'in',
                    'weight' => '0.61',
                    'width' => '3.75',
                    'height' => '10.57',
                    'length' => '3.75',
                    'clicks_counter' => 0,
                    'sales_count' => 0,
                    'parent_id' => NULL,
                    'homepage_order' => NULL,
                ),
                12 => 
                array (
                    'id' => 13,
                    'name' => 'Perforated Towels - 25 Sheets - 2 Pack ',
                    'slug' => 'perforated-towels-25-sheets-2-pack',
                    'item_id' => '605',
                    'sku' => '605',
                    'upc' => '7-16554-00605-3',
                    'quantity_per_case' => '8',
                    'weight_uom' => 'lbs',
                    'length_uom' => 'in',
                    'height_uom' => 'in',
                    'width_uom' => 'in',
                    'weight' => '1.15',
                    'width' => '3.50',
                    'height' => '10.75',
                    'length' => '7.35',
                    'clicks_counter' => 0,
                    'sales_count' => 0,
                    'parent_id' => '295',
                    'homepage_order' => NULL,
                ),
                13 => 
                array (
                    'id' => 14,
                    'name' => 'Perforated Towels - 100 Sheets - 2 Pack ',
                    'slug' => 'perforated-towels-100-sheets-2-pack',
                    'item_id' => '296',
                    'sku' => '296',
                    'upc' => '7-16554-00296-3',
                    'quantity_per_case' => '4',
                    'weight_uom' => 'lbs',
                    'length_uom' => 'in',
                    'height_uom' => 'in',
                    'width_uom' => 'in',
                    'weight' => '0.00',
                    'width' => '0.00',
                    'height' => '0.00',
                    'length' => '0.00',
                    'clicks_counter' => 1,
                    'sales_count' => 0,
                    'parent_id' => NULL,
                    'created_at' => '2019-12-24 15:38:34',
                    'updated_at' => '2020-01-03 16:48:30',
                    'brand_id' => NULL,
                    'manufacture_id' => NULL,
                    'availability_id' => NULL,
                    'homepage_order' => NULL,
                ),
                14 => 
                array (
                    'id' => 15,
                    'name' => 'Perforated Pet Towels - 50 Sheets',
                    'slug' => 'perforated-pet-towels-50-sheets',
                    'item_id' => '608',
                    'sku' => '608',
                    'upc' => '7-16554-00608-4',
                    'quantity_per_case' => '12',
                    'weight_uom' => 'lbs',
                    'length_uom' => 'in',
                    'height_uom' => 'in',
                    'width_uom' => 'in',
                    'weight' => '0.00',
                    'width' => '0.00',
                    'height' => '0.00',
                    'length' => '0.00',
                    'clicks_counter' => 0,
                    'sales_count' => 0,
                    'parent_id' => NULL,
                    'homepage_order' => NULL,
                ),
                15 => 
                array (
                    'id' => 16,
                    'name' => 'Ultimate Shop Towel - 50 Sheets',
                    'slug' => 'ultimate-shop-towel-50-sheets',
                    'item_id' => '614',
                    'sku' => '614',
                    'upc' => '7-16554-00614-3',
                    'cost' => '0.000000',
                    'price' => '9.990000',
                    'quantity_per_case' => '6',
                    'weight_uom' => 'lbs',
                    'length_uom' => 'in',
                    'height_uom' => 'in',
                    'width_uom' => 'in',
                    'weight' => '0.00',
                    'width' => '0.00',
                    'height' => '0.00',
                    'length' => '0.00',
                    'clicks_counter' => 0,
                    'sales_count' => 0,
                    'parent_id' => NULL,
                    'homepage_order' => NULL,
                ),
                16 => 
                array (
                    'id' => 17,
                    'name' => 'Compostable Trash/Waste Bags - Small - 3 Gallon - 30 Bags',
                    'slug' => 'compostable-trashwaste-bags-small-3-gallon-30-bags',
                    'item_id' => '00601-12',
                    'sku' => '00601-12',
                    'upc' => '7-16554-00601-5',
                    'cost' => '0.000000',
                    'price' => '10.990000',
                    'quantity_per_case' => '12',
                    'weight_uom' => 'lbs',
                    'length_uom' => 'in',
                    'height_uom' => 'in',
                    'width_uom' => 'in',
                    'weight' => '0.60',
                    'width' => '2.50',
                    'height' => '2.50',
                    'length' => '7.00',
                    'clicks_counter' => 0,
                    'sales_count' => 0,
                    'parent_id' => NULL,
                    'homepage_order' => NULL,
                ),
                17 => 
                array (
                    'id' => 18,
                    'name' => 'Compostable Trash/Waste Bags - Small - 3 Gallon - 128 Bags',
                    'slug' => 'compostable-trashwaste-bags-small-3-gallon-128-bags',
                    'item_id' => '637',
                    'sku' => '637',
                    'upc' => '7-16554-0637-4',
                    'quantity_per_case' => '6',
                    'weight_uom' => 'lbs',
                    'length_uom' => 'in',
                    'height_uom' => 'in',
                    'width_uom' => 'in',
                    'weight' => '2.64',
                    'width' => '2.60',
                    'height' => '5.00',
                    'length' => '10.00',
                    'clicks_counter' => 1,
                    'sales_count' => 0,
                    'parent_id' => '00601-12',
                    'created_at' => '2019-12-24 15:38:34',
                    'updated_at' => '2020-01-03 02:35:59',
                    'brand_id' => NULL,
                    'manufacture_id' => NULL,
                    'availability_id' => NULL,
                    'homepage_order' => NULL,
                ),
                18 => 
                array (
                    'id' => 19,
                    'name' => 'Compostable Trash/Waste Bags - Tall - 13 Gallon - 12 Bags',
                    'slug' => 'compostable-trashwaste-bags-tall-13-gallon-12-bags',
                    'item_id' => '00603-12',
                    'sku' => '00603-12',
                    'upc' => '7-16554-00603-9',
                    'cost' => '0.000000',
                    'price' => '9.990000',
                    'quantity_per_case' => '12',
                    'weight_uom' => 'lbs',
                    'length_uom' => 'in',
                    'height_uom' => 'in',
                    'width_uom' => 'in',
                    'weight' => '0.70',
                    'width' => '2.50',
                    'height' => '2.50',
                    'length' => '7.00',
                    'clicks_counter' => 8,
                    'sales_count' => 0,
                    'parent_id' => NULL,
                    'created_at' => '2019-12-24 15:38:34',
                    'updated_at' => '2020-01-04 05:44:59',
                    'brand_id' => NULL,
                    'manufacture_id' => NULL,
                    'availability_id' => NULL,
                    'homepage_order' => NULL,
                ),
                19 => 
                array (
                    'id' => 20,
                    'name' => 'Compostable Trash/Waste Bags - Tall - 13 Gallon - 100 Bags',
                    'slug' => 'compostable-trashwaste-bags-tall-13-gallon-100-bags',
                    'item_id' => '600',
                    'sku' => '600',
                    'upc' => '7-16554-00600-8',
                    'quantity_per_case' => NULL,
                    'weight_uom' => 'lbs',
                    'length_uom' => 'in',
                    'height_uom' => 'in',
                    'width_uom' => 'in',
                    'weight' => '0.00',
                    'width' => '0.00',
                    'height' => '0.00',
                    'length' => '0.00',
                    'clicks_counter' => 0,
                    'sales_count' => 0,
                    'parent_id' => '00603-12',
                    'homepage_order' => NULL,
                ),
                20 => 
                array (
                    'id' => 21,
                'name' => 'Compostable Trash/Waste Bags - Tall - 13 Gallon - 100 Bags (Drawstring)',
                    'slug' => 'compostable-trashwaste-bags-tall-13-gallon-100-bags-drawstring',
                    'item_id' => '600',
                    'sku' => '600',
                    'upc' => '7-16554-00600-8',
                    'quantity_per_case' => '6',
                    'weight_uom' => 'lbs',
                    'length_uom' => 'in',
                    'height_uom' => 'in',
                    'width_uom' => 'in',
                    'weight' => '0.00',
                    'width' => '0.00',
                    'height' => '0.00',
                    'length' => '0.00',
                    'clicks_counter' => 0,
                    'sales_count' => 0,
                    'parent_id' => '00603-12',
                    'homepage_order' => NULL,
                ),
                21 => 
                array (
                    'id' => 22,
                    'name' => 'Compostable Trash/Waste Bags - Extra Large - 39 Gallon - 5 Bags',
                    'slug' => 'compostable-trashwaste-bags-extra-large-39-gallon-5-bags',
                    'item_id' => '00606-12',
                    'sku' => '00606-12',
                    'upc' => '7-16554-00606-0',
                    'cost' => '0.000000',
                    'price' => '10.990000',
                    'quantity_per_case' => '12',
                    'weight_uom' => 'lbs',
                    'length_uom' => 'in',
                    'height_uom' => 'in',
                    'width_uom' => 'in',
                    'weight' => '0.90',
                    'width' => '2.50',
                    'height' => '2.50',
                    'length' => '9.00',
                    'clicks_counter' => 0,
                    'sales_count' => 0,
                    'parent_id' => NULL,
                    'homepage_order' => NULL,
                ),
                22 => 
                array (
                    'id' => 23,
                    'name' => 'Compostable Trash/Waste Bags - Extra Large - 39 Gallon - 30 Bags',
                    'slug' => 'compostable-trashwaste-bags-extra-large-39-gallon-30-bags',
                    'item_id' => '278',
                    'sku' => '278',
                    'upc' => '7-16554-00278-9',
                    'quantity_per_case' => '4',
                    'weight_uom' => 'lbs',
                    'length_uom' => 'in',
                    'height_uom' => 'in',
                    'width_uom' => 'in',
                    'weight' => '0.00',
                    'width' => '0.00',
                    'height' => '0.00',
                    'length' => '0.00',
                    'clicks_counter' => 0,
                    'sales_count' => 0,
                    'parent_id' => '00606-12',
                    'homepage_order' => NULL,
                ),
                23 => 
                array (
                    'id' => 24,
                    'name' => 'Compostable Pet Trash Bags - 60 Bags',
                    'slug' => 'compostable-pet-trash-bags-60-bags',
                    'item_id' => '00609-12',
                    'sku' => '00609-12',
                    'upc' => '7-16554-00609-1',
                    'cost' => '0.000000',
                    'price' => '5.990000',
                    'quantity_per_case' => '12',
                    'weight_uom' => 'lbs',
                    'length_uom' => 'in',
                    'height_uom' => 'in',
                    'width_uom' => 'in',
                    'weight' => '0.45',
                    'width' => '1.65',
                    'height' => '6.25',
                    'length' => '3.40',
                    'clicks_counter' => 0,
                    'sales_count' => 0,
                    'parent_id' => NULL,
                    'homepage_order' => NULL,
                ),
                24 => 
                array (
                    'id' => 25,
                    'name' => 'Compostable Fruit/Vegetable Bags - 1000 Bags',
                    'slug' => 'compostable-fruitvegetable-bags-1000-bags',
                    'item_id' => '621',
                    'sku' => '621',
                    'upc' => NULL,
                    'quantity_per_case' => '2',
                    'weight_uom' => 'lbs',
                    'length_uom' => 'in',
                    'height_uom' => 'in',
                    'width_uom' => 'in',
                    'weight' => '0.00',
                    'width' => '0.00',
                    'height' => '0.00',
                    'length' => '0.00',
                    'clicks_counter' => 0,
                    'sales_count' => 0,
                    'parent_id' => NULL,
                    'homepage_order' => NULL,
                ),
                25 => 
                array (
                    'id' => 26,
                    'name' => 'Bamboo Floor Wipes - 20 Wipes',
                    'slug' => 'bamboo-floor-wipes-20-wipes',
                    'item_id' => '611',
                    'sku' => '611',
                    'upc' => '7-16554-00611-4',
                    'cost' => '0.000000',
                    'price' => '10.990000',
                    'quantity_per_case' => '12',
                    'weight_uom' => 'lbs',
                    'length_uom' => 'in',
                    'height_uom' => 'in',
                    'width_uom' => 'in',
                    'weight' => '0.40',
                    'width' => '4.75',
                    'height' => '5.00',
                    'length' => '6.00',
                    'parent_id' => NULL,
                    'homepage_order' => NULL,
                ),
                26 => 
                array (
                    'id' => 27,
                    'name' => 'Bamboo Floor Wipes - 100 Wipes',
                    'slug' => 'bamboo-floor-wipes-100-wipes',
                    'item_id' => '302',
                    'sku' => '302',
                    'upc' => '7-16554-00302-1',
                    'weight_uom' => 'lbs',
                    'length_uom' => 'in',
                    'height_uom' => 'in',
                    'width_uom' => 'in',
                    'weight' => '1.70',
                    'width' => '4.50',
                    'height' => '11.10',
                    'length' => '11.50',
                    'parent_id' => '611',
                    'homepage_order' => NULL,
                ),
                27 => 
                array (
                    'id' => 28,
                    'name' => 'Bamboo Wet Floor Wipes - 20 Wipes',
                    'slug' => 'bamboo-wet-floor-wipes-20-wipes',
                    'item_id' => '615',
                    'sku' => '615',
                    'upc' => '7-16554-00615-2',
                    'weight_uom' => 'lbs',
                    'length_uom' => 'in',
                    'height_uom' => 'in',
                    'width_uom' => 'in',
                    'weight' => '0.88',
                    'width' => '2.00',
                    'height' => '8.25',
                    'length' => '11.50',
                    'parent_id' => NULL,
                    'homepage_order' => NULL,
                ),
            );

            foreach ($products as $product)
            {
                factory(App\Product::class)->create([
                    'name'          => $product['name'],
                    'slug'          => $product['slug'],
                    'upc'           => $product['upc'],
                    'weight'        => $product['weight'],
                    'width'         => $product['width'],
                    'length'        => $product['length'],
                    'height'        => $product['height'],
                    'weight_uom'    => $product['weight_uom'],
                    'width_uom'     => $product['width_uom'],
                    'length_uom'    => $product['length_uom'],
                    'height_uom'    => $product['height_uom'],
                    'parent_id'     => $product['parent_id'],
                    'homepage_order'       => $product['homepage_order']
                ]);
            }

       } catch(Exception $e) {
         throw new Exception('Exception occur ' . $e);

         \DB::rollBack();
       }

       \DB::commit();
    }
}
